# Generated by Django 4.0.3 on 2022-09-04 10:11

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='model')),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('company', models.CharField(max_length=150)),
                ('front_camera', models.PositiveIntegerField(default=0)),
                ('back_camera', models.PositiveIntegerField(default=0)),
                ('cpu', models.CharField(max_length=200)),
                ('ram', models.PositiveIntegerField(default=0)),
                ('memory', models.PositiveIntegerField(default=0)),
                ('battery', models.PositiveIntegerField(default=0)),
                ('os', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['company'],
            },
        ),
    ]
