# Generated by Django 4.0.3 on 2022-09-06 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phone', '0002_phone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='back_camera',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='phone',
            name='battery',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='phone',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phone',
            name='cpu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='phone',
            name='front_camera',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='phone',
            name='memory',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='phone',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
