# Generated by Django 4.0.3 on 2022-09-06 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charger', '0003_alter_charger_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0001_initial'),
        ('accessory', '0001_initial'),
        ('phone', '0002_phone_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='photo_account/%Y%m/%d')),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('goods_accessory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g_accessory', to='accessory.accessory')),
                ('goods_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g_case', to='case.case')),
                ('goods_charger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g_charger', to='charger.charger')),
                ('goods_phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g_phone', to='phone.phone')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
