# Generated by Django 4.0.3 on 2022-09-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='goods_accessory',
        ),
        migrations.RemoveField(
            model_name='account',
            name='goods_case',
        ),
        migrations.RemoveField(
            model_name='account',
            name='goods_charger',
        ),
        migrations.RemoveField(
            model_name='account',
            name='goods_phone',
        ),
    ]
