# Generated by Django 4.0.3 on 2022-09-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_goods_accessory_account_goods_case_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
