# Generated by Django 4.0.3 on 2022-09-05 13:40

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='model')),
                ('content', models.TextField()),
                ('power', models.PositiveIntegerField(default=0)),
                ('company', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='charger.type')),
            ],
            options={
                'ordering': ['model'],
            },
        ),
    ]
