# Generated by Django 4.0.3 on 2022-09-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0002_charger_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charger',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
